#!/usr/bin/env node

const fs = require('fs')
const http = require('http')

const port = process.argv.length > 2
  ? process.argv[2]
  : 80

const handler = (req, res) => {
  const path = req.url

  if (path.startsWith('/js/') || path.startsWith('/css/') || path.startsWith('/images')) {
    fs.createReadStream(path.slice(1)).pipe(res)
  } else if (path.startsWith('/about.html')) {
    fs.createReadStream('about.html').pipe(res)
  } else {
    fs.createReadStream('blob.html').pipe(res)
  }
}

const main = () => http
  .createServer(handler)
  .listen(port)

main()
